### ISSUE TITLE
hi, I might find a bug in "Models/WITRAN.py".

### ISSUE THREAD

**Issue by VV1314** [Water2sea/WITRAN#1] opened 2023-10-19 13:23 UTC
"Temporal_feature_dim" is defined, only when "freq" is "h". So when "freq" is other parameter, what is the "Temporal_feature_dim"?

**Comment by Water2sea** [comment] 2023-10-20 05:27
Hello, it's nice to see your interest in our work. The issue you raised is not a bug. In our paper, it is explicitly stated that due to the different original acquisition granularities of each dataset, in order to ensure that they contain the same semantic information on the same task, our experiments are conducted by aggregating them into one hour. 'Temporal_feature_dim' represents the input dimension of the temporal feature. When 'freq' is 'h', 'Temporal_feature_dim' is 4. However, 'Temporal_feature_dim' can also be changed according to the variation of 'freq'. More specific details can be found in our paper, which will be released soon.

**Comment by VV1314** [comment] 2023-10-20 07:58
Thank you for your reply, and looking for your paper online! And then, I find a issue in "data_factory.py", the parameters "detail_freq" is not defined, maybe it refers to "freq"?

**Comment by Water2sea** [comment] 2023-10-20 09:18
'detail_freq' is only needed when making individual predictions with the model. It is not required during the entire process of model training, validation, and testing. If you want to use this parameter, you can refer to the instructions of Autoformer for specific details.

**Closed as completed** 2023-10-20 09:18 UTC
